#ifndef MOVEGEN_H_INCLUDED
#define MOVEGEN_H_INCLUDED

#include "defs.h"
#include "board.h"

#define MAX_GAME_MOVES 512

/*
 * Use a MoveList to store all of the moves that are generated by 
 * generateAllMoves. Each MoveList stores all the possible moves for a single
 * board position, including pseudo-legal moves (moves that leave the king in
 * check).
 * 
 * numMoves:     An integer storing the number of moves in the MoveList. The 
 *               number of moves in the list cannot exceed MAX_GAME_MOVES.
 * moves:        An array of moves. Each move contains multiple pieces of 
 *               information which is combined into 1 64-bit integer.
 */
typedef struct {
    int numMoves;
    uint64 moves[MAX_GAME_MOVES];
} MoveList;

void generateAllMoves(const Board* board, MoveList* list);

#endif
